### ISSUE TITLE
Unset offerCount on the variation offer

### ISSUE THREAD

**Issue by webdados** [leewillis77/wc-structured-data-option-3#1]
You should probably unset "offerCount" from the variation offer because it's not an "AggregateOffer"

**Comment by leewillis77** [comment]
Hi; 

I've updated this, although I will note that I've seen more success from people using this snippet instead (which already includes that change):

https://github.com/leewillis77/wc-structured-data-option-4

**Comment by webdados** [comment]
Thanks. I was under the impression that you recommended option 3. My bad.

So you are now recommending ditching the "AggregateOffer" and only keep the "Offer" on variation URLs, right?

I must confess this always seemed like the best option for me but, as I said, reading the original ticket on woocommerce github I was under the impression people were using option 3.

**Comment by leewillis77** [comment]
We don't *formally* recommend anything as there's no guidance from Google as to what exactly they expect. You're right that the GH issue history suggested (3), but I've had dialogue with other customers via our support channels that suggests that (4) may be better. 

The aggregateOffer output by WooCommerce core seems to cause issues on its own for some customers, so I think treating the variation URL as a simple "1 product" may be more helpful rather than trying to represent it as one of many.

At this point though it does seem to vary by customer so I'd encourage you to use whichever works for you. All feedback is useful though.

**Comment by webdados** [comment]
I gave some feedback on the other option :-)
